import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Page, Grid, Text, Button, Spacer, Divider } from '@geist-ui/core'
import Navbar from '../conponents/Navbar'
import { SP } from 'next/dist/shared/lib/utils'

export default function Home() {
  return (

    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Page>
          <Page.Header center={true}>
            <Navbar />

          </Page.Header>
          <Page.Content>
            <Grid.Container justify="center">
              <Text p>
                Hi 👋 I am
              </Text>
            </Grid.Container>
            <Grid.Container style={{margin:0}} justify="center">
              <Text style={{fontSize: '96px', fontWeight: 800, letterSpacing:"-0.05em", margin:0}} justify="center">UI/UX designer.</Text>
            </Grid.Container>
            <Grid.Container justify="center">
              <Text style={{fontSize: '96px', fontWeight: 800, letterSpacing:"-0.05em",margin:0}}>Developer.</Text>
            </Grid.Container>
            <Grid.Container justify="center">
              <Text style={{fontSize: '96px', fontWeight: 800,letterSpacing:"-0.05em",margin:0}}>Game security Enthusiast.</Text>
            </Grid.Container>

            <Spacer h={2} />

            <Grid.Container justify="center">
              <Button shadow type="secondary">Get in touch</Button>
            </Grid.Container>

            <Spacer h={10} />

            <Grid.Container>
              <Text h1>I am a university student studying at the Hang Seng University of Hong Kong and enrolled in BSC (Hons) in Applied Computing.</Text>
              <Spacer h={5} />
              <Text h1>Experienced <Text h1 type='warning'>UI/UX designer</Text> and <Text h1 type='warning'>Software engineer</Text> with multiple satisfied clients with my modern, accessible, and inclusive design. </Text><Text></Text><Text></Text>
              <Spacer h={5} />
              <Text h1 type='primary'>Highly self-motivated, able to work under pressure who is also a fast learner. Good communication skills, also able to solve problems by using the best solution quickly.</Text>
            </Grid.Container>

            <Spacer h={10} />

            <Grid.Container justify='center'>
              <Text h1>Featured Projects</Text>
            </Grid.Container>
            <Grid.Container justify='center'>
              <Image width="2048" height="1170" src="/geist-banner.png" alt="my projects" />
            </Grid.Container>
            <Grid.Container justify='center'>
              <Text h6 type='secondary'>GeistUI - A p100 framework</Text>
            </Grid.Container>

            <Spacer h={5} />

            <Grid.Container gap={5} justify="center">
              <Grid xs={12} direction="column" justify='center'>
                <Text h4 type="secondary">Spokenbot</Text>
                <Text h2>The next generation AI-powered learning app.</Text>
                <Spacer h={2} />
                <Button ghost type="secondary" scale={2 / 3}>Learn more</Button>
              </Grid>
              <Grid xs={12} justify="center">
                <Image width={429} height={705} src="/placeholder.png" alt="Project 01"></Image>
              </Grid>
            </Grid.Container>

            <Spacer h={5} />

            <Grid.Container gap={5} justify="center">
              <Grid xs={12} direction="column" justify='center'>
                <Text h4 type="secondary">Discordbot</Text>
                <Text h2>The ultimate solution for tailor-made discord management system.</Text>
                <Spacer h={2} />
                <Button ghost type="secondary" scale={2 / 3}>Learn more</Button>
              </Grid>
              <Grid xs={12} justify="center">
                <Image width={429} height={705} src="/placeholder.png" alt="Project 02"></Image>
              </Grid>
            </Grid.Container>

            <Spacer h={5} />

            <Grid.Container gap={5} justify="center">
              <Grid xs={12} direction="column" justify='center'>
                <Text h4 type="secondary">Design concept</Text>
                <Text h2>Spokenbot</Text>
                <Spacer h={2} />
                <Button ghost type="secondary" scale={2 / 3}>Learn more</Button>
              </Grid>
              <Grid xs={12} justify="center">
                <Image width={429} height={705} src="/placeholder.png" alt="Project 03"></Image>
              </Grid>
            </Grid.Container>

            <Spacer h={5} />


            <Grid.Container gap={5} justify="center">
              <Button ghost type="secondary" scale={2 / 3}>Check more</Button>
            </Grid.Container>

            <Spacer h={10} />

            <Grid.Container direction='column' gap={2}>
              <Text h1>My skillsets</Text>
              <Text p>Want to know what skills do I have to make a perfect fit to your company?</Text>
            </Grid.Container>

            <Spacer h={2} />

            <Grid.Container gap={5} justify="center">
              <Grid xs={12} direction="column">
                <Text h3 type="secondary">Design concept</Text>
                <Text p>Figma is my current productive tool to make my UI & UX designs, multiple high-quality projects were being made with the usage of Figma.</Text>
                <Grid.Container direction='column'>
                  <ul>
                    <li>
                      <Text h4>Figma</Text>
                    </li>
                    <li>
                      <Text h4>Adobe XD</Text>
                    </li>
                    <li>
                      <Text h4>Heroin Handoff</Text>
                    </li>
                    <li>
                      <Text h4>Adobe After Effects</Text>
                    </li>
                  </ul>
                </Grid.Container>
              </Grid>
              <Grid xs={12} direction="column">
                <Text h3 type="secondary">Javascript</Text>
                <Text p>Been using NodeJS for backend projects, using reactJS for web projects and React Native for cross-platform android apps.</Text>
                <Grid.Container direction='column'>
                  <ul>
                    <li>
                      <Text h4>React.js</Text>
                    </li>
                    <li>
                      <Text h4>React Native</Text>
                    </li>
                    <li>
                      <Text h4>Express.js</Text>
                    </li>
                    <li>
                      <Text h4>TypeScript</Text>
                    </li>
                  </ul>
                </Grid.Container>
              </Grid>
              <Grid xs={12} direction="column">
                <Text h3 type="secondary">Java</Text>
                <Text p>Java is my essential gateway to get started into computer engineering with android apps development</Text>
                <Grid.Container direction='column'>
                  <ul>
                    <li>
                      <Text h4>Android App development</Text>
                    </li>
                    <li>
                      <Text h4>Java Enterprise (JSP)</Text>
                    </li>
                  </ul>
                </Grid.Container>
              </Grid>
              <Grid xs={12} direction="column">
                <Text h3 type="secondary">Video editing</Text>
                <Text p>Video editing and compositing is always a hobby of mine, and I have been doing video compositing for concept implementation.</Text>
                <Grid.Container direction='column'>
                  <ul>
                    <li>
                      <Text h4>Adobe Premiere pro</Text>
                    </li>
                    <li>
                      <Text h4>Heroin Handoff</Text>
                    </li>
                    <li>
                      <Text h4>Final Cut Pro</Text>
                    </li>
                  </ul>
                </Grid.Container>
              </Grid>
              <Grid xs={12} direction="column">
                <Text h3 type="secondary">Devops</Text>
                <Text p>DevOps is useful to boost my productivity and automate project deployment and testing.</Text>
                <Grid.Container direction='column'>
                  <ul>
                    <li>
                      <Text h4>Docker</Text>
                    </li>
                    <li>
                      <Text h4>Tarvis CI</Text>
                    </li>
                  </ul>
                </Grid.Container>
              </Grid>
              <Grid xs={12} direction="column">
                <Text h3 type="secondary">System Adminstration</Text>
                <Text p>As a home lab administrator, I have these skills to manage the servers in my home.</Text>
                <Grid.Container direction='column'>
                  <ul>
                    <li>
                      <Text h4>Powershell Scripting</Text>
                    </li>
                    <li>
                      <Text h4>Linux shell scripting</Text>
                    </li>
                  </ul>
                </Grid.Container>
              </Grid>
            </Grid.Container>

            <Spacer h={10} />

            <Grid.Container direction='column' gap={2}>
              <Text h1>Want to get in touch?</Text>
              <Text p>You can find me in these platforms:</Text>
            </Grid.Container>

            <Spacer h={5} />
            <Grid.Container justify={"center"} gap={20}>
              <Grid>
                <Image width={96} height={96} src="/twitter.svg" />
              </Grid>
              <Grid>
                <Image width={96} height={96} src="/github.svg" />
              </Grid>
              <Grid>
                <Image width={96} height={96} src="/behance.svg" />
              </Grid>
            </Grid.Container>

            <Spacer h={10} />

          </Page.Content>
          <Page.Footer>
            <footer>
              <Divider />
              <Spacer h={2} />
              <Text h6> Greetings from Hong Kong! </Text>

            </footer>
          </Page.Footer>
        </Page>
      </main>
    </div>
  )
}
